"""add cleaned_records.column_type

Revision ID: 25adb566e926
Revises: 5e88d2c39f94
Create Date: 2026-09-08 18:03:24.657117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25adb566e926'
down_revision: Union[str, Sequence[str], None] = '5e88d2c39f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cleaned_records', sa.Column('column_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cleaned_records', 'column_type')
    # ### end Alembic commands ###
