"""initial schema

Revision ID: 54d337cae21d
Revises: 
Create Date: 2026-09-08 17:23:11.016086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54d337cae21d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_corrections',
    sa.Column('feedback_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('column_type', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=False),
    sa.Column('agent_output', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('feedback_id'),
    sa.UniqueConstraint('column_type', 'original_value', name='uq_feedback_column_type_original_value')
    )
    op.create_table('raw_uploads',
    sa.Column('upload_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='uploadstatus', native_enum=False, length=20), nullable=False),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_table('audit_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['raw_uploads.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('ix_audit_log_upload_id', 'audit_log', ['upload_id'], unique=False)
    op.create_table('cleaned_records',
    sa.Column('record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('cleaned_value', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 100', name='ck_confidence_score_range'),
    sa.ForeignKeyConstraint(['upload_id'], ['raw_uploads.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('ix_cleaned_records_upload_column', 'cleaned_records', ['upload_id', 'column_name'], unique=False)
    op.create_index('ix_cleaned_records_upload_confidence', 'cleaned_records', ['upload_id', 'confidence_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cleaned_records_upload_confidence', table_name='cleaned_records')
    op.drop_index('ix_cleaned_records_upload_column', table_name='cleaned_records')
    op.drop_table('cleaned_records')
    op.drop_index('ix_audit_log_upload_id', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('raw_uploads')
    op.drop_table('feedback_corrections')
    # ### end Alembic commands ###
