"""add raw_uploads.insights_json

Revision ID: b8151bef1165
Revises: c990bc8d39c5
Create Date: 2026-09-08 18:22:20.035849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8151bef1165'
down_revision: Union[str, Sequence[str], None] = 'c990bc8d39c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_uploads', sa.Column('insights_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_uploads', 'insights_json')
    # ### end Alembic commands ###
