"""add cleaned_records.row_index

Revision ID: c990bc8d39c5
Revises: 25adb566e926
Create Date: 2026-09-08 18:19:33.320060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c990bc8d39c5'
down_revision: Union[str, Sequence[str], None] = '25adb566e926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cleaned_records', sa.Column('row_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cleaned_records', 'row_index')
    # ### end Alembic commands ###
